<?php
/**
 * Diglin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 *
 * @category    Diglin
 * @package     Diglin_
 * @copyright   Copyright (c) 2011-2012 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<li class="fields">
    <div class="field">
        <label for="github_login" class="required"><em>*</em><?php echo $this->__('Github Username') ?></label>
        <div class="input-box">
            <input type="text" name="github_login" id="github_login" title="<?php echo $this->__('Github Username') ?>" class="input-text required-entry" />
            <p><?php echo $this->__("You can also <a href='%s'>login</a> with your Github account. You won't need to provide any password for our website and some information will be pre-filled for you.", $this->getUrl('github/account/login'));?></p>
        </div>
    </div>
</li>