<?php
/**
 * Diglin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 *
 * @category    Diglin
 * @package     Diglin_
 * @copyright   Copyright (c) 2011-2012 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="box-account box-info">
    <div class="box-head">
        <h2><?php echo $this->__('Additional Information') ?></h2>
    </div>
    <div class="col2-set">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                <h3><?php echo $this->__('Github Information') ?></h3>
                </div>
                <div class="box-content">
                    <p>
                        <?php echo $this->__('Username: ') . $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getGithubLogin()) ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
