<?php
/**
 * Diglin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 *
 * @category    Diglin
 * @package     Diglin_Github
 * @copyright   Copyright (c) 2011-2013 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Mage_Core_Block_Template */

$header = $this->getHeader();

if (empty($header)) {
    $header = '2';
}
?>
<div class="github-login">
    <?php echo sprintf('<h%s>', $header) . $this->__('Login with your Github account.') . sprintf('</h%s>', $header) ; ?>
    <?php echo $this->getChildHtml('github.button'); ?>
</div>