<?php
/**
 * Diglin
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 *
 * @category    Diglin
 * @package     Diglin_Github
 * @copyright   Copyright (c) 2011-2013 Diglin (http://www.diglin.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/* @var $this Diglin_Github_Block_Account_Register */
?>
<div class="account-create">
    <div class="page-title"><h1><?php echo $this->__('Create an account thanks to your Github account') ?></h1></div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php /* Extensions placeholder */ ?>
    <?php echo $this->getChildHtml('customer.form.register.extra')?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" name="github_customer_create">
        <div class="fieldset">
            <input type="hidden" name="github_id" id="github_id" value="<?php echo $this->escapeHtml($this->getFormData()->getGithubId()); ?>" />
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <div class="content">
                <p><?php echo $this->__('We need some information to help us to communicate with you. Please, fill in the required fields to create your account on our website.');?><br/>
                <?php echo $this->__('We filled for you some information based on your public Github profile. No password necessary.');?></p>
            </div>

            <ul class="right">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/github/octocat.png')?>" alt="<?php echo $this->__('Github Octocat');?>" title="<?php echo $this->__('Github Octocat');?>" style="width:250px;"/>
                </li>
            </ul>

            <ul class="form-list left">
                <li class="fields">
                    <label for="github_login"><?php echo $this->__('Github Username') ?></label>
                    <div class="input-box">
                        <input type="text" name="github_login" id="github_login" value="<?php echo $this->escapeHtml($this->getFormData()->getGithubLogin()) ?>" title="<?php echo $this->__('Github Username') ?>" disabled />
                    </div>
                </li>
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li class="fields">
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
                </li>
                <?php endif ?>
            </ul>
            <div class="clearer"></div>
        </div>

        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <?php if (!$this->getChild('form_fields_after')): ?><p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p><?php endif; ?>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
    //]]>
    </script>
    <?php echo $this->getChildHtml('form_fields_after')?>
</div>